server:
  port: 8773

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/  # 注册中心

spring:
  application:
    name: eureka-provider  # 服务名

feign:
  hystrix:
    enabled: true
